version: '2.1'

services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        restart: always
        volumes:
            - rabbitmq-data-volume:/var/lib/rabbitmq
            - rabbitmq-log-volume:/var/log/rabbitmq
            - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME:-guest}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-guest}
        ports:
            - ${MANAGEMENT_UI_HTTP_PORT:-8080}:15672
            - ${AMQP091_PORT:-5672}:5672
            - ${PROMETHEUS_PORT:-15692}:15692
        # healthcheck:
        #     test: curl -f https://localhost:40700 || exit 1

    server:
        container_name: microservice-server
        build: .
        # restart: on-failure
        depends_on:
            - rabbitmq
                # condition: service_healthy
            - mongo
            - consul
        links:
            - rabbitmq
            - mongo
            - consul
        volumes:
            - 'projects-repository:/projects'
        ports:
            - '3001:3000'

    mongo:
        image: mongo
        restart: always
        volumes:
            - 'mongo-data:/data/db'
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        depends_on:
            - mongo
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}

    consul:
        image: consul
        environment:
        - CONSUL_BIND_INTERFACE=eth0
        ports:
        - 5000:8500
        - 5001:8600
        networks:
        - consul-network

volumes:
    mongo-data:
    projects-repository:
    rabbitmq-data-volume:
    rabbitmq-log-volume:

networks:
  consul-network: