version: '3'

services:
    server:
        container_name: microservice-server
        build: .
        ports:
            - '3001:3000'

    mongo:
        image: mongo
        restart: always
        volumes:
            - './data:/data/db'
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        depends_on:
            - mongo
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
