version: '3'

# Add your networks/volumes/services for your microservice
services:
  server:
    container_name: projects-ci
    image: esgimicroci/al1-projects:latest
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - './.docker/volume/projects-repository:/projects-repository'
    ports:
      - '3011:3000'

  mongo:
    image: mongo
    restart: always
    volumes:
      - 'mongo-data:/data/db'
    ports:
      - 27099:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

volumes:
  mongo-data:
  projects-repository:
